services:
  app:
    build:
      dockerfile: Dockerfile.flog
      context: scripts/flog
    command: ["flog", "-l", "-d", "5", "-s", "5", "-w", "-o", "/app-logs/app.log"]
    container_name: app 
    volumes:
      - app-logs:/app-logs

  vector:
    image: timberio/vector:latest-alpine
    container_name: vector
    environment:
      - VECTOR_CONFIG_TOML=/etc/vector/vector.toml
    volumes:
      - app-logs:/var/log/app:ro
      - ./scripts/vector/vector.toml:/etc/vector/vector.toml:ro
    tmpfs:
      - /etc/vector
    depends_on:
      - app
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    
  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.4
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - xpack.security.enabled=false
    ports:
      - "5601:5601"

volumes:
  app-logs:

networks:
  default:
