logger:
  enable: true
  pretty_backtrace: true
  level: debug
  format: compact

server:
  port: 5150
  binding: localhost
  host: http://localhost
  middlewares:
    fallback:
      enable: false
    static:
      enable: true
      must_exist: true
      precompressed: false
      folder:
        uri: "/"
        path: "frontend/dist"
      fallback: "frontend/dist/index.html"

workers:
  mode: BackgroundAsync

mailer:
  smtp:
    enable: true
    host: localhost
    port: 1025
    secure: false
database:
  uri: {{ get_env(name="DATABASE_URL", default="sqlite://lottalogs_production.sqlite?mode=rwc") }}
  enable_logging: false
  connect_timeout: {{ get_env(name="DB_CONNECT_TIMEOUT", default="500") }}
  idle_timeout: {{ get_env(name="DB_IDLE_TIMEOUT", default="500") }}
  min_connections: {{ get_env(name="DB_MIN_CONNECTIONS", default="1") }}
  max_connections: {{ get_env(name="DB_MAX_CONNECTIONS", default="1") }}
  auto_migrate: true
  dangerously_truncate: false
  dangerously_recreate: false

settings:
  elasticsearch_url: http://localhost:9200
