name: Test
on:
  push:
    branches:
      - '**'
      - '!main'
    tags-ignore:
      - '**'

env:
  RUST_TOOLCHAIN: stable
  TOOLCHAIN_PROFILE: minimal

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    permissions:
      contents: read
    
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}
      - name: Build frontend
        run: npm install && npm run build
        working-directory: ./frontend
      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features --all
        env:
          REDIS_URL: redis://localhost:${{job.services.redis.ports[6379]}}
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres_test
          
